### ISSUE TITLE
test,  train as doc ids

### ISSUE THREAD

**Issue by natalink** [natalink/mwe_noske#4]
Should we put document names as doc id's so that users know from which corpus an example comes from?

**Comment by Ansa211** [comment]
Yes, I think we should put document names as doc id's.
We discussed the issue of separating test and train data with Dan Zeman (relating to UD corpora). He thinks, and I agree, that the division of test and train is not particularly important for the kind of research one does with corpus query systems such as KonText, so we decided all data should be pusblished in one corpus. However, it should be simple enough to create a subcorpus consisting only of the train data. I am not sure how to set it up in the registry file, but I'll try to have a look at it.

(If you agree with this solution, I suggest you leave this task open and assign it to me. I cannot self-assign, probably something to do with rights on the project.)
