### ISSUE TITLE
NoSke or|and KonText

### ISSUE THREAD

**Issue by natalink** [natalink/mwe_noske#9]
Guys, 
because there is a high probability that the scheme got changed for the PARSEME corpora, I suggest that @Ansa211 makes a page devoted to it (smth like https://ufal.mff.cuni.cz/lindat-kontext/parseme ) and reflect all the changes that may come there. You can put the links to the corpora locations there as well.  (both KonText and NoSke) 
To the discussion should the data be hosted on KonText or Behrang's NoSke, I would argue for both.
 
**Pro's for KonText:** 
- KonText is well maintained, new features are added regularly
- maybe some day we can have possibility to browse trees 
- there can be a link from LINDAT item in a repo to the query system

**Con's for KonText:**
- user has to spend some time trying to login. If her/his university may have some issues with Shibboleth, it may be necessary to contact the Uni IT team, so at some point the user may give up:)
- The feature Ansa mentioned at the paper -  _overlaps/sub-hits filter_ works in NoSke, but not in KonText, right? It's not a big con though, since I believe not many users will be so proficient in SkE platform to use it.

**Pro's for NoSke:**
- the user will not have to be logged in to access such basic functions as _Frequency_ or _Collocations_ 
- _overlaps/sub-hits filter_  thing

**Con's for NoSke:**
- only Behrang maintains it, no new features are added
- there is no such thing as a corpus list like in KonText, right? So you had to send us links to all the corpora 

**CON for both** (or maybe I'm mistaken, correct me): There is no way how to link to all the corpora at once. For NoSke, you need to change the corpora in the first query form. In KonText the corpora are stored under "Multiple corpora", but as far as I remember when I worked on KonText, I could not link to it, I could link only to "Monolingual" corplist.

**Comment by languagerecipes** [comment]
hi Natalia,

As said adding the data to noske is not a problem and there is no need for
justification; I will add a footnote to the paper with a proper link
address.
From the paper, can you try to remove comments and unwanted information and
try to finalize sections? Who is adding screenshots?
Not much time left for submission :)

Thank you

Behrang

**Comment by languagerecipes** [comment]
this is not really relevant to the paper. the message is clear and you have
already propose it in the earlier 2016 paper of yours; maybe you can say
how this work is different from your 2016 paper instead?!
